server:
  port: 8087
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/mall_full_link?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: admin
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid
  redis:
    host: localhost
    database: 1
    port: 6379
#    password: admin
    timeout: 3000ms
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: admin
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
redis:
  database: mall
  key:
    admin: 'ums:admin'
  expire:
    common: 86400 # 24Сʱ
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI4G1VRffC4D7CmBv5dFwZ
    accessKeySecret: v8afbIbKpjPqiI26slcdXQHB0kjJDR
    bucketName: perfo7
    policy:
      expire: 300
    maxSize: 10
    callback: http://localhost:8080/aliyun/oss/callback
    dir:
      prefix: mall/images/
minio:
  endpoint: http://localhost:9090
  bucketName: mall
  accessKey: minioadmin
  secretKey: minioadmin
feign:
  okhttp:
    enabled: true
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 3000