apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: mall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2023-07-18T17-49-40Z
        env:
        - name: MINIO_ROOT_USER
          value: minioadmin
        - name: MINIO_ROOT_PASSWORD
          value: minioadmin
        ports:
        - containerPort: 9000
        - containerPort: 9001
        command: ["minio", "server", "/data", "--console-address", ":9001"]
        volumeMounts:
        - mountPath: /data
          name: minio-storage
      volumes:
      - name: minio-storage
        persistentVolumeClaim:
          claimName: minio-pvc



---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 31090
    name: minio-port
  - port: 9001
    targetPort: 9001
    nodePort: 31091
    name: minio-management-port
  selector:
    app: minio
  type: NodePort