apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentinel
  template:
    metadata:
      labels:
        app: sentinel
    spec:
      containers:
      - name: sentinel
        image: bladex/sentinel-dashboard:1.8.6
        env:
        - name: JAVA_OPTS
          value: "-Dserver.port=8080 -Dcsp.sentinel.dashboard.server=localhost:8080 -Dproject.name=sentinel-dashboard"
        ports:
        - containerPort: 8858 

---
apiVersion: v1
kind: Service
metadata:
  name: sentinel
spec:
  ports:
  - port: 8858
    targetPort: 8858
  selector:
    app: sentinel